{
  blogs {
    _id
    title
    text
    image
    imageURL
    tags
    author {
      _id
      firstName
      lastName
    }
    category{
      _id
      title
      parent
    }
    comments{
      _id
      comment
      parent
      show
      section
      createdAt
    }
    likes
    dislikes
  }
}